name: Deploy to EC2 with Docker

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@<EC2_PUBLIC_IP> << 'EOF'
          cd ~/fastapi-app || git clone https://github.com/opula1234/Python_Employee_Management.git ~/fastapi-app
          cd ~/fastapi-app
          git pull origin main
          docker stop fastapi-app || true
          docker rm fastapi-app || true
          docker build -t fastapi-app .
          docker run -d -p 8000:8000 --name fastapi-app fastapi-app
        EOF
