name: Deploy FastAPI App to EC2 via Docker

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up SSH access
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # - name: Install Docker on EC2 (if needed)
      #   run: |
      #     ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} '
      #       if ! command -v docker &> /dev/null; then
      #         echo "Installing Docker..."
      #         sudo apt update && sudo apt install -y docker.io
      #         sudo systemctl start docker
      #         sudo systemctl enable docker
      #         sudo usermod -aG docker ubuntu
      #         echo "Docker installation complete."
      #       else
      #         echo "Docker already installed."
      #       fi
      #     '

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} '
            echo "Cloning or updating repo..."
            if [ ! -d ~/fastapi-app ]; then
              git clone https://github.com/opula1234/Python_Employee_Management.git ~/fastapi-app
            fi

            cd ~/fastapi-app
            git pull origin main

            echo "Stopping existing container (if any)..."
            docker stop fastapi-app || true
            docker rm fastapi-app || true

            echo "Building and starting Docker container..."
            docker build -t fastapi-app .
            docker run -d -p 8000:8000 --name fastapi-app fastapi-app
          '
